import Header from './components/Header';                                                                                                                                                                                   
  import ModelViewer from './components/ModelViewer';                                                                                                                                                                         
  import './App.css';                                                                                                                                                                                                         
                                                                                                                                                                                                                              
  function App() {                                                                                                                                                                                                            
    return (                                                                                                                                                                                                                  
      <div style={{ display: 'flex', flexDirection: 'column', height: '100vh', width: '100vw', overflow: 'hidden' }}>                                                                                                         
        <Header />                                                                                                                                                                                                            
        <main style={{ flex: 1, position: 'relative', background: '#111' }}>                                                                                                                                                  
          <ModelViewer />                                                                                                                                                                                                     
        </main>                                                                                                                                                                                                               
      </div>                                                                                                                                                                                                                  
    );                                                                                                                                                                                                                        
  }                                                                                                                                                                                                                           
  export default App;   